version: 2

models:
  - name: stg_policies
    description: "Raw policy data"
    columns:
      - name: policy_id
        description: "Policy ID"
        tests:
          - unique
          - not_null
      - name: product_code
        tests:
          - not_null
      - name: status
        tests:
          - not_null
          - accepted_values:
              values: ["ACTIVE", "CANCELLED", "EXPIRED"]

  - name: stg_policy_versions
    description: "Policy version and premium data"
    columns:
      - name: version_id
        tests:
          - unique
          - not_null
      - name: policy_id
        tests:
          - not_null

  - name: stg_insureds
    description: "Insured person data"
    columns:
      - name: insured_id
        tests:
          - unique
          - not_null
      - name: policy_id
        tests:
          - not_null